#!/bin/bash

# Describe the AWS account and user for AWS CLI 
# By Ed ODonnell
#
# Version : 20241004

AWS_INFO=$(aws sts get-caller-identity --output text)
ACCOUNT_ID=$(echo $AWS_INFO | awk '{print $1}')
ACCOUNT_ALIAS=$(aws iam list-account-aliases --query "AccountAliases[0]" --output text)
USER_NAME=$(echo $AWS_INFO | awk '{print $2}' | cut -d'/' -f2)

echo " "
echo "Account ID: $ACCOUNT_ID"
echo "Account Alias: $ACCOUNT_ALIAS"
echo "Username: $USER_NAME"
echo " "


